name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_publish:
    name: Building '${{ matrix.version }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [6, 7, 8, 9, 10, latest]

    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/dummy.Dockerfile
        # build-args: VERSION=${{ matrix.version }}
        tags: hpc_compiletools_gcc:${{ matrix.version }}
        push: false
        load: true
    - name: List all available images
      run: docker image ls

    # - name: Login to DockerHub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - name: Build
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./dockerfiles/gcc.Dockerfile
    #     build-args: VERSION=${{ matrix.version }}
    #     tags: hpc_compiletools_gcc:${{ matrix.version }}
    #     push: false
    # - name: Run tests
    #   run: ./runtest.sh hpc_compiletools_gcc:${{ matrix.version }}
    # - name: Push
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./dockerfiles/gcc.Dockerfile
    #     build-args: VERSION=${{ matrix.version }}
    #     tags: ahelm/hpc_compiletools_gcc:${{ matrix.version }}
    #     push: true