name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: Build the Docker image
    #   run: docker build . --file dockerfiles/gcc.Dockerfile --tag hpc_compiletools/gcc:latest
    # - name: Run tests
    #   run: sudo ./runtest.sh
    - name: Build simple image
      run: docker build . --file dockerfiles/ubuntu-test.Dockerfile --tag testcontainer:latest
    - name: Fixes permission for writing
      run: echo $USER
    - name: Echo user name of docker container
      run: docker run -v $(pwd):/project testcontainer:latest bash -c "id"
    - name: Echo user name of docker container
      run: docker run -v $(pwd):/project testcontainer:latest bash -c "cat /etc/passwd"
    - name: Run minitest.sh
      run: ./minitest.sh testcontainer:latest

