name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
    # - name: Build the Docker image
    #   run: docker build . --file dockerfiles/gcc.Dockerfile --tag hpc_compiletools/gcc:latest
    # - name: Run tests
    #   run: ./runtest.sh hpc_compiletools/gcc:latest
    # - name: Push to GitHub Packages
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./dockerfiles/dummy.Dockerfile
    #     push: true
    #     tags: ahelm/dummy:latest

    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/dummy.Dockerfile
        tags: dummy:latest
        push: true